config/routes.rb
Rails.application.routes.draw do
  get 'about', to: 'static_pages#about'
  get 'booklets', to: 'static_pages#booklets'
  get 'contact', to: 'static_pages#contact'
  get 'expertise', to: 'static_pages#expertise'
  get 'home', to: 'static_pages#home'
  get 'judgements', to: 'static_pages#judgements'
  get 'news', to: 'static_pages#news'
  get 'videos', to: 'static_pages#videos'

  root to: 'static_pages#home'

  devise_for :users

  resources :booklets, only: [:show]
  resources :posts, only: [:show]

  namespace :admin do
    resources :booklets
    resources :judgements
    resources :posts
    resources :users

    root to: 'dashboard#index'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about; end

  def booklets
    @booklets = Booklet.by_created_date
  end

  def contact; end

  def expertise; end

  def home
    @posts = Post.recent
  end

  def judgements
    @judgements = Judgement.by_created_date
  end

  def news
    @posts = Post.by_created_date
  end

  def videos; end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/booklets.html.erb
<div class="ui container booklets">
  <div class="ui horizontal divider">
    <h2 class="ui center aligned header">CARTILHAS E MANUAIS</h2>
  </div>
  <div class="ui divided relaxed items">
    <% @booklets.each do |booklet| %>
      <%= link_to booklet_path(booklet), class: 'item' do %>
        <i class="<%= attachment_icon_class(booklet.attachment.content_type) %>"></i>
        <div class="content">
          <div class="header">
            <%= booklet.title %>
          </div>
          <div class="meta">
            <p>
              Ano de lançamento: <%= booklet.year %>
            </p>
            <p>
              Categoria: <%= booklet_category_i18n(booklet.category) %>
            </p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/static_pages/contact.html.erb
<div class="ui container contact">
  <div class="ui horizontal divider">
    <h2 class="ui center aligned header">CONTATO</h2>
  </div>
  <div class="ui relaxed items">
    <div class="item">
      <div class="ui image">
        <i class="huge call icon"></i>
      </div>
      <div class="content">
        <div class="header">
          AGENDE SUA VISITA
        </div>
        <div class="description">
          <p class="">Você pode entrar em contato conosco pelos telefones (62) 3215-7777 ou
            (62) 3215-7700.</p>
        </div>
        <div class="extra">
        </div>
      </div>
    </div>
    <div class="item">
      <div class="ui image">
        <i class="huge map outline icon"></i>
      </div>
      <div class="content">
        <div class="header">
          ENDEREÇO
        </div>
        <div class="description">
          <p>O IBEDEC-GO está localizado na Rua 5, número 1011 (acima da Praça Tamandaré), Setor Oeste, Goiânia/GO.</p>
        </div>
        <div class="extra">
        </div>
      </div>
    </div>
  </div>
  <div class="map">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3821.8125287431326!2d-49.26580388447436!3d-16.686262149968147!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x935ef1681e7b78fd%3A0x7cb28a47596f1a2b!2sIBEDEC+-+Instituto+Brasileiro+de+Estudo+e+Defesa+das+Rela%C3%A7%C3%B5es+de+Consumo!5e0!3m2!1spt-BR!2sbr!4v1499373473379" width="800" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
  </div>
</div>

app/views/static_pages/expertise.html.erb
<div class="ui container expertise">
  <div class="ui horizontal divider">
    <h2 class="ui center aligned header">ÁREAS DE ATUAÇÃO</h2>
  </div>
  <div class="ui relaxed divided items">
    <div class="item">
      <div class="ui image">
        <i class="massive building outline icon"></i>
      </div>
      <div class="content">
        <div class="header">
          CONSTRUTORAS
        </div>
        <div class="description">
          <p>Em nosso dia-a-dia de atendimento e orientação ao consumidor, são muitas as dúvidas que surgem neste tipo de contrato de consumo, o que ensejou a sua abordagem através das nossas <%= link_to 'cartilhas e manuais', booklets_path %> visando garantir os direitos dos consumidores.</p>
          <p>Esperamos que este material didático lhe seja de grande valia e contamos com sua colaboração para enriquecê-lo a cada ano, com novas sugestões que você pode nos falar <%= link_to 'clicando aqui', contact_path %>.</p>
        </div>
      </div>
    </div>
    <div class="item">
      <div class="ui image">
        <i class="massive mobile icon"></i>
      </div>
      <div class="content">
        <div class="header">
          TELEFONIA
        </div>
        <div class="description">
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dignissim egestas dui, et semper ligula bibendum nec. Praesent sapien augue, molestie sit amet laoreet non, accumsan in lorem. Pellentesque non mollis felis, id efficitur neque. Donec id ultrices tortor, vitae tempus odio. Vestibulum diam magna, tincidunt vitae ultrices id, consectetur ut est. Duis tristique at sapien nec tincidunt. Maecenas non ante lacinia est aliquam ultricies at in mauris. Suspendisse elementum vel lectus eget luctus. Donec risus eros, fermentum a neque ornare, euismod aliquet nisi. Nam laoreet tellus at lorem blandit, nec varius enim ultricies. Cras congue nulla non est feugiat molestie.</p>
        </div>
      </div>
    </div>
    <div class="item">
      <div class="ui image">
        <i class="massive doctor icon"></i>
      </div>
      <div class="content">
        <div class="header">
          PLANOS DE SAÚDE
        </div>
        <div class="description">
          <p>Diante de uma legislação ineficiente, a ANS (Agência Nacional de Saúde Suplementar), tenta aplicar penalidades às operadoras diante dos desrespeitos perante o consumidor.</p>
          <p>O Ibedec Goiás, preocupado com esses abusos, trabalha diariamente em prol dos consumidores afetados por operadoras de plano de saúde. Você pode acompanhar alguns resultados do nosso trabalho <%= link_to 'clicando aqui', judgements_path %>
        </div>
      </div>
    </div>
    <div class="item">
      <div class="ui image">
        <i class="massive money icon"></i>
      </div>
      <div class="content">
        <div class="header">
          FINANCIAMENTO BANCÁRIO
        </div>
        <div class="description">
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dignissim egestas dui, et semper ligula bibendum nec. Praesent sapien augue, molestie sit amet laoreet non, accumsan in lorem. Pellentesque non mollis felis, id efficitur neque. Donec id ultrices tortor, vitae tempus odio. Vestibulum diam magna, tincidunt vitae ultrices id, consectetur ut est. Duis tristique at sapien nec tincidunt. Maecenas non ante lacinia est aliquam ultricies at in mauris. Suspendisse elementum vel lectus eget luctus. Donec risus eros, fermentum a neque ornare, euismod aliquet nisi. Nam laoreet tellus at lorem blandit, nec varius enim ultricies. Cras congue nulla non est feugiat molestie.</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="intro-header">
  <div class="intro">
    <h1 class="title">IBEDEC GOIÁS</h1>
    <p class="paragraph">Desde 2010 atuando na defesa dos consumidores goianos</p>
    <button class="ui inverted large call-to-action button">RECEBA NOSSAS NOTÍCIAS</button>
  </div>
</div>

<div class="ui container stats">
  <div class="ui horizontal divider">
    <h2 class="ui center aligned header">NOSSOS NÚMEROS</h2>
  </div>
  <div class="ui statistics">
    <div class="statistic">
      <div class="value">
        +9.000
      </div>
      <div class="label">
        atendimentos gratuitos
      </div>
    </div>
    <div class="statistic">
      <div class="value">
        +20.000
      </div>
      <div class="label">
        alguma coisa incrível
      </div>
    </div>
    <div class="statistic">
      <div class="value">
        +30
      </div>
      <div class="label">
        outra coisa incrível por mês
      </div>
    </div>
  </div>
</div>

<div class="ui container news">
  <div class="ui horizontal divider">
    <h2 class="ui center aligned header">ÚLTIMAS NOTÍCIAS</h2>
  </div>
  <div class="ui three stackable cards">
    <% @posts.each do |post| %>
      <%= link_to post_path(post), class: 'card' do %>
        <div class="image">
          <%= image_tag post.image.url %>
        </div>
        <div class="content">
          <div class="header"><%= post.title %></div>
        </div>
        <div class="extra content">
          <div>
            <i class="clock icon"></i>
            <%= l(post.created_at) %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= link_to news_path, class: 'ui right floated blue inverted button' do %>
    Mais notícias
    <i class="right chevron icon"></i>
  <% end %>
</div>

app/views/static_pages/judgements.html.erb
<div class="ui container judgements">
  <div class="ui horizontal divider">
    <h2 class="ui center aligned header">SENTENÇAS E DECISÕES</h2>
  </div>
  <div class="ui divided relaxed items">
    <% @judgements.each do |judgement| %>
      <%= link_to judgement.attachment.url, class: 'item' do %>
          <i class="<%= attachment_icon_class(judgement.attachment.content_type) %>"></i>
          <div class="content">
            <div class="header">
              <%= judgement.title %>
            </div>
            <div class="meta">
              <p>
                Adicionada em: <%= l(judgement.created_at) %>
              </p>
              <p>
                Categoria: <%= judgement_category_i18n(judgement.category) %>
              </p>
            </div>
          </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/static_pages/news.html.erb
<div class="ui container news">
  <div class="ui horizontal divider">
    <h2 class="ui center aligned header">NOTÍCIAS</h2>
  </div>
  <div class="ui three stackable cards">
    <% @posts.each do |post| %>
      <%= link_to post_path(post), class: 'card' do %>
        <div class="image">
          <%= image_tag post.image.url %>
        </div>
        <div class="content">
          <div class="header"><%= post.title %></div>
        </div>
        <div class="extra content">
          <div>
            <i class="clock icon"></i>
            <%= l(post.created_at) %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/static_pages/videos.html.erb
<h1>StaticPages#videos</h1>
<p>Find me in app/views/static_pages/videos.html.erb</p>