config/routes.rb
Rails.application.routes.draw do
  get 'about', to: 'static_pages#about'
  get 'booklets', to: 'static_pages#booklets'
  get 'contact', to: 'static_pages#contact'
  get 'expertise', to: 'static_pages#expertise'
  get 'home', to: 'static_pages#home'
  get 'judgements', to: 'static_pages#judgements'
  get 'news', to: 'static_pages#news'
  get 'videos', to: 'static_pages#videos'

  root to: 'static_pages#home'

  devise_for :users

  resources :booklets, only: [:show]
  resources :posts, only: [:show]

  namespace :admin do
    resources :booklets
    resources :judgements
    resources :posts
    resources :users

    root to: 'dashboard#index'
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="ui red message">
    <div class="header">A validação falhou:</div>
    <ul class="list">
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, value| %>
  <div class="ui <%= flash_message_class(type) %> message">
    <% if value.kind_of?(Array) %>
      <ul class="list">
        <% value.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% else %>
      <%= value %>
    <% end %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="ui stackable secondary mobile hidden menu">
  <%= link_to root_path, class: 'item logo' do %>
    <%= image_tag 'logo.png', class: 'ui rounded small image' %>
  <% end %>
  <div class="right menu">
    <%= link_to 'O IBEDEC', about_path, class: 'item' %>
    <%= link_to 'Notícias', news_path, class: 'item' %>
    <%= link_to 'Vídeos', videos_path, class: 'item' %>
    <%= link_to 'Áreas de atuação', expertise_path, class: 'item' %>
    <%= link_to 'Sentenças e decisões', judgements_path, class: 'item' %>
    <%= link_to 'Cartilhas e manuais', booklets_path, class: 'item' %>
    <%= link_to 'Contato', contact_path, class: 'item' %>
    <% if user_signed_in? %>
      <div class="ui user-avatar dropdown item">
        <%= image_tag current_user.avatar.url(:medium), class: 'ui circular user-avatar image' %>
        <div class="menu">
          <%= link_to 'Painel de administrador', admin_root_path, class: 'item' %>
          <%= link_to 'Alterar dados', edit_user_registration_path, class: 'item' %>
          <%= link_to 'Sair', destroy_user_session_path, method: :delete, class: 'item' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="mobile only menu">
  <%= link_to root_path, class: 'item logo' do %>
    <%= image_tag 'logo.png', class: 'ui rounded small image' %>
  <% end %>
  <a href="#" class="menu item toggle">
    <i class="black large content icon"></i>
  </a>
  <div class="ui vertical inverted fluid menu">
    <%= link_to 'Início', home_path, class: 'item' %>
    <%= link_to 'O IBEDEC', about_path, class: 'item' %>
    <%= link_to 'Notícias', news_path, class: 'item' %>
    <%= link_to 'Vídeos', videos_path, class: 'item' %>
    <%= link_to 'Áreas de atuação', expertise_path, class: 'item' %>
    <%= link_to 'Sentenças e decisões', judgements_path, class: 'item' %>
    <%= link_to 'Cartilhas e manuais', booklets_path, class: 'item' %>
    <%= link_to 'Contato', contact_path, class: 'item' %>
    <% if user_signed_in? %>
      <%= link_to 'Painel de administrador', admin_root_path, class: 'item' %>
      <%= link_to 'Alterar dados', edit_user_registration_path, class: 'item' %>
      <%= link_to 'Sair', destroy_user_session_path, method: :delete, class: 'item' %>
    <% end %>
  </div>
</div>