config/routes.rb
Rails.application.routes.draw do
  get 'about', to: 'static_pages#about'
  get 'booklets', to: 'static_pages#booklets'
  get 'contact', to: 'static_pages#contact'
  get 'expertise', to: 'static_pages#expertise'
  get 'home', to: 'static_pages#home'
  get 'judgements', to: 'static_pages#judgements'
  get 'news', to: 'static_pages#news'
  get 'videos', to: 'static_pages#videos'

  root to: 'static_pages#home'

  devise_for :users

  resources :booklets, only: [:show]
  resources :posts, only: [:show]

  namespace :admin do
    resources :booklets
    resources :judgements
    resources :posts
    resources :users

    root to: 'dashboard#index'
  end
end

app/models/booklet.rb
class Booklet < ApplicationRecord
  enum category: %i[construction sfh sfi social_security consumer]

  belongs_to :user, optional: true

  validates :title, presence: true
  validates :year, presence: true, numericality: { only_integer: true }
  validates :category, presence: true

  has_attached_file :attachment
  validates_attachment :attachment, presence: true, content_type: {
    content_type: %w[
      application/pdf
      application/msword
      application/vnd.openxmlformats-officedocument.wordprocessingml.document
    ]
  }

  scope :by_created_date, -> { order(created_at: :desc) }
end

app/controllers/admin/booklets_controller.rb
class Admin::BookletsController < AdminController
  before_action :set_booklet, only: %i[show edit update destroy]

  # GET /booklets
  def index
    @booklets = Booklet.by_created_date
  end

  # GET /booklets/1
  def show; end

  # GET /booklets/new
  def new
    @booklet = Booklet.new
  end

  # GET /booklets/1/edit
  def edit; end

  # POST /booklets
  def create
    @booklet = Booklet.new(booklet_params)
    @booklet.user = current_user

    if @booklet.save
      redirect_to admin_booklet_url(@booklet), notice: 'Cartilha criada com sucesso.'
    else
      render :new
    end
  end

  # PATCH/PUT /booklets/1
  def update
    if @booklet.update(booklet_params)
      redirect_to admin_booklet_url(@booklet), notice: 'Cartilha atualizada com sucesso.'
    else
      render :edit
    end
  end

  # DELETE /booklets/1
  def destroy
    @booklet.destroy
    redirect_to admin_booklets_url, notice: 'Cartilha excluída com sucesso.'
  end

  private

  def set_booklet
    @booklet = Booklet.find(params[:id])
  end

  def booklet_params
    params.require(:booklet).permit(
      :title,
      :description,
      :year,
      :category,
      :attachment
    )
  end
end

app/controllers/booklets_controller.rb
class BookletsController < ApplicationController
  before_action :set_booklet

  def show; end

  private

  def set_booklet
    @booklet = Booklet.find(params[:id])
  end
end

app/helpers/admin/booklets_helper.rb
module Admin::BookletsHelper
  def booklet_category_i18n(key)
    t("activerecord.attributes.booklet.categories.#{key}")
  end

  def booklet_category_options
    Booklet.categories.map { |key, _value| [booklet_category_i18n(key), key] }
  end
end

app/views/admin/booklets/_form.html.erb
<%= form_for [:admin, @booklet], html: { class: 'ui form' } do |f| %>
    <%= render 'shared/error_messages', object: @booklet %>

    <div class="ui grid">
      <div class="row">
        <div class="column">
          <div class="field">
            <%= f.label :title %>
            <%= f.text_field :title, required: true %>
          </div>
          <div class="field">
            <%= f.label :description %>
            <%= f.cktext_area :description %>
          </div>
          <div class="field">
            <%= f.label :year %>
            <%= f.number_field :year, required: true %>
          </div>
          <div class="field">
            <%= f.label :category %>
            <%= f.select :category, booklet_category_options, { include_blank: 'Selecione uma categoria' }, required: true %>
          </div>
          <div class="field">
            <%= f.label :attachment %>
            <%= f.file_field :attachment %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="column">
          <%= f.submit 'Enviar', class: 'ui submit fluid blue inverted button' %>
        </div>
      </div>
    </div>
<% end %>

app/views/admin/booklets/edit.html.erb
<%= render 'form' %>

app/views/admin/booklets/index.html.erb
<%= link_to new_admin_booklet_path, class: 'ui fluid green inverted button' do %>
    <i class="book icon"></i>
    Criar cartilha
<% end %>

<div class="ui divided relaxed items">
  <% @booklets.each do |booklet| %>
      <div class="item">
        <i class="<%= attachment_icon_class(booklet.attachment.content_type) %>"></i>
        <div class="content">
          <div class="header">
            <%= booklet.title %>
          </div>
          <div class="meta">
            <p>
              Ano de lançamento: <%= booklet.year %>
            </p>
            <p>
              Criada em: <%= l(booklet.created_at) %>
            </p>
            <p>
              Categoria: <%= booklet_category_i18n(booklet.category) %>
            </p>
          </div>
          <div class="extra">
            <%= link_to admin_booklet_path(booklet), class: 'ui mini green inverted button' do %>
                <i class="unhide icon"></i>
                Visualizar
            <% end %>
            <%= link_to edit_admin_booklet_path(booklet), class: 'ui mini blue inverted button' do %>
                <i class="edit icon"></i>
                Editar
            <% end %>
            <%= link_to admin_booklet_path(booklet), class: 'ui mini red inverted button', data: {confirm: 'Você tem certeza?'}, method: :delete do %>
                <i class="trash icon"></i>
                Excluir
            <% end %>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/admin/booklets/new.html.erb
<%= render 'form' %>

app/views/admin/booklets/show.html.erb
<div class="ui items">
  <div class="item">
    <div class="content">
      <div class="header">
        <%= @booklet.title %>
      </div>
      <div class="description">
        <p>
          Ano de lançamento: <%= @booklet.year %>
        </p>
        <p>
          Adicionada por: <%= @booklet.user.full_name if @booklet.user %>
        </p>
        <p>
          Criada em: <%= l(@booklet.created_at) %>
        </p>
        <p>
          Categoria: <%= booklet_category_i18n(@booklet.category) %>
        </p>
        <p>
          Documento: <%= link_to @booklet.attachment.original_filename, @booklet.attachment.url, target: '_blank' %>
        </p>
        <p>
          Descrição: <%= @booklet.description.html_safe %>
        </p>
      </div>
      <div class="extra">
        <%= link_to edit_admin_booklet_path(@booklet), class: 'ui mini blue inverted button' do %>
            <i class="edit icon"></i>
            Editar
        <% end %>
        <%= link_to admin_booklet_path(@booklet), class: 'ui mini red inverted button', data: {confirm: 'Você tem certeza?'}, method: :delete do %>
            <i class="trash icon"></i>
            Excluir
        <% end %>
      </div>
    </div>
  </div>
</div>