config/routes.rb
Rails.application.routes.draw do
  get 'about', to: 'static_pages#about'
  get 'booklets', to: 'static_pages#booklets'
  get 'contact', to: 'static_pages#contact'
  get 'expertise', to: 'static_pages#expertise'
  get 'home', to: 'static_pages#home'
  get 'judgements', to: 'static_pages#judgements'
  get 'news', to: 'static_pages#news'
  get 'videos', to: 'static_pages#videos'

  root to: 'static_pages#home'

  devise_for :users

  resources :booklets, only: [:show]
  resources :posts, only: [:show]

  namespace :admin do
    resources :booklets
    resources :judgements
    resources :posts
    resources :users

    root to: 'dashboard#index'
  end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IBEDEC-GO</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui container">
      <%= render 'shared/navbar' %>
      <div class="ui divider"></div>
      <div class="ui stackable grid">
        <div class="four wide column">
          <div class="ui secondary vertical pointing fluid menu">
            <%= link_to 'Início', admin_root_path, class: "item #{active_menu_item_class(admin_root_path)}" %>
            <%= link_to 'Cartilhas', admin_booklets_path, class: "item #{active_menu_item_class(admin_booklets_path)}" %>
            <%= link_to 'Notícias', admin_posts_path, class: "item #{active_menu_item_class(admin_posts_path)}" %>
            <%= link_to 'Usuários', admin_users_path, class: "item #{active_menu_item_class(admin_users_path)}" %>
            <%= link_to 'Sentenças', admin_judgements_path, class: "item #{active_menu_item_class(admin_judgements_path)}" %>
          </div>
        </div>
        <div class="twelve wide column">
          <%= render 'shared/flash_messages' %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IBEDEC-GO</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui container">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flash_messages' %>
    </div>
    <div class="ui stackable grid">
      <div class="column">
        <%= yield %>
      </div>
    </div>
  </body>
</html>